name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_run:
    workflows: ["build"]
    branches: [master]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts for release
        uses: dawidd6/action-download-artifact@v6
        with:
           path: dist
           workflow: build.yml
      - name: Rename artifacts
        run: |
          mv dist/pterocli-macos-amd64/pterocli pterocli-macos-amd64
          mv dist/pterocli-linux-amd64/pterocli pterocli-linux-amd64
          mv dist/pterocli-win-amd64.exe/pterocli.exe pterocli-win-amd64.exe

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          #body_path: ./RELEASE_CHANGELOG
          files: |
            pterocli-macos-amd64
            pterocli-linux-amd64
            pterocli-win-amd64.exe