name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts for release
        uses: dawidd6/action-download-artifact@v6
        with:
           workflow: build.yml
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            pterocli*/*