name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts for release
        uses: actions/download-artifact@v4
        with:
          path:  target/*/release/

      - name: Release
        uses: softprops/action-gh-release@v2